# Generated by Django 5.0.6 on 2024-07-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_alter_item_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("text", "list")},
        ),
    ]
